import { createFileRoute } from "@tanstack/react-router";
import { NavBar } from "@/components/NavBar";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Use — EcoLife" },
      { name: "description", content: "The Terms of Use for EcoLife — an AI-powered upcycling companion." },
      { property: "og:title", content: "Terms of Use — EcoLife" },
      { property: "og:description", content: "The Terms of Use for EcoLife — an AI-powered upcycling companion." },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-background font-sans text-foreground antialiased">
      <NavBar />
      <section className="mx-auto w-full max-w-3xl px-6 py-16 md:px-10 md:py-24">
        <p className="mb-5 text-xs uppercase tracking-[0.22em] text-[color:var(--sage)]">Legal</p>
        <h1 className="font-serif text-4xl leading-tight text-foreground md:text-5xl">Terms of Use</h1>
        <p className="mt-3 text-sm font-light text-foreground/60">Last updated: July 8, 2026</p>

        <div className="mt-10 space-y-10 text-base font-light leading-relaxed text-foreground/80">
          <Section title="1. Acceptance of Terms">
            <p>
              By creating an account and using EcoLife, you agree to these Terms of Use. If you are under 13,
              you must have parental or guardian consent to use this app.
            </p>
          </Section>

          <Section title="2. About Our AI-Generated Content">
            <p>
              All DIY project recipes on EcoLife are generated by an artificial intelligence model
              (Google Gemini). These recipes are creative suggestions only. They are not professionally
              verified craft or safety instructions. EcoLife does not guarantee the accuracy, safety, or
              completeness of any AI-generated recipe. You follow these instructions entirely at your own risk.
            </p>
          </Section>

          <Section title="3. Your Responsibilities">
            <ul className="ml-5 list-disc space-y-2">
              <li>
                You must provide an accurate date of birth at signup. Providing a false date of birth to
                bypass safety filters is a violation of these terms.
              </li>
              <li>
                You must only upload images of household waste items, not images of people, private spaces,
                or copyrighted material.
              </li>
              <li>
                You are responsible for verifying that any DIY project is safe before attempting it,
                especially when tools are involved.
              </li>
              <li>Users under 16 must have adult supervision when using any tools mentioned in a recipe.</li>
            </ul>
          </Section>

          <Section title="4. Limitation of Liability">
            <p>
              EcoLife and its developers are not liable for any injury, damage, or loss resulting from
              following AI-generated recipes. The app is a creative tool, not a certified safety guide.
            </p>
          </Section>

          <Section title="5. Account Deletion">
            <p>
              You may delete your account at any time. All personal data including your date of birth will
              be permanently deleted upon account closure.
            </p>
          </Section>

          <Section title="6. Changes to These Terms">
            <p>
              We may update these Terms at any time. Continued use of the app after changes constitutes
              acceptance of the new terms.
            </p>
          </Section>
        </div>
      </section>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="font-serif text-2xl text-foreground">{title}</h2>
      <div className="mt-3 space-y-3">{children}</div>
    </div>
  );
}
